import type { CatalogCar } from "@/lib/catalog/types";

const DEFAULT_IMAGE = "/card-example.jpg";

export const catalogCars: CatalogCar[] = [
  {
    id: "veh-1001",
    slug: "toyota-corolla-2-0-se-g-cvt-2021",
    brand: "Toyota",
    model: "Corolla",
    version: "2.0 SE-G CVT",
    type: "usados",
    year: 2021,
    km: 93000,
    priceArs: 37400000,
    transmission: "Automatica",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1002",
    slug: "ford-fiesta-kinetic-se-plus-2018",
    brand: "Ford",
    model: "Fiesta",
    version: "Kinetic SE Plus",
    type: "usados",
    year: 2018,
    km: 74200,
    priceArs: 16500000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1003",
    slug: "volkswagen-t-cross-trendline-1-0t-at-2024",
    brand: "Volkswagen",
    model: "T-Cross",
    version: "Trendline 1.0T AT",
    type: "nuevos",
    year: 2024,
    km: 0,
    priceArs: 39500000,
    transmission: "Automatica",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1004",
    slug: "peugeot-2008-allure-1-6-2017",
    brand: "Peugeot",
    model: "2008",
    version: "Allure 1.6",
    type: "usados",
    year: 2017,
    km: 189700,
    priceArs: 18000000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
  {
    id: "veh-1005",
    slug: "nissan-kicks-advance-cvt-2020",
    brand: "Nissan",
    model: "Kicks",
    version: "Advance CVT",
    type: "usados",
    year: 2020,
    km: 65400,
    priceArs: 27900000,
    transmission: "Automatica",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1006",
    slug: "chevrolet-tracker-ltz-1-2t-at-2023",
    brand: "Chevrolet",
    model: "Tracker",
    version: "LTZ 1.2T AT",
    type: "nuevos",
    year: 2023,
    km: 0,
    priceArs: 35200000,
    transmission: "Automatica",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
  {
    id: "veh-1007",
    slug: "fiat-cronos-drive-1-3-gse-2022",
    brand: "Fiat",
    model: "Cronos",
    version: "Drive 1.3 GSE",
    type: "usados",
    year: 2022,
    km: 28100,
    priceArs: 24800000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1008",
    slug: "honda-civic-ext-2-0-cvt-2019",
    brand: "Honda",
    model: "Civic",
    version: "EXT 2.0 CVT",
    type: "usados",
    year: 2019,
    km: 81500,
    priceArs: 29800000,
    transmission: "Automatica",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
  {
    id: "veh-1009",
    slug: "toyota-hilux-2-8-srx-4x4-at-2022",
    brand: "Toyota",
    model: "Hilux",
    version: "2.8 SRX 4x4 AT",
    type: "usados",
    year: 2022,
    km: 59000,
    priceArs: 56900000,
    transmission: "Automatica",
    fuel: "Diesel",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1010",
    slug: "ford-ranger-3-0-v6-limited-4x4-at-2024",
    brand: "Ford",
    model: "Ranger",
    version: "3.0 V6 Limited 4x4 AT",
    type: "nuevos",
    year: 2024,
    km: 0,
    priceArs: 68400000,
    transmission: "Automatica",
    fuel: "Diesel",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1011",
    slug: "volkswagen-gol-trend-1-6-2020",
    brand: "Volkswagen",
    model: "Gol",
    version: "Trend 1.6",
    type: "usados",
    year: 2020,
    km: 92300,
    priceArs: 16900000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
  {
    id: "veh-1012",
    slug: "renault-sandero-intens-1-6-2021",
    brand: "Renault",
    model: "Sandero",
    version: "Intens 1.6",
    type: "usados",
    year: 2021,
    km: 48600,
    priceArs: 19500000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
  {
    id: "veh-1013",
    slug: "toyota-corolla-cross-xei-hv-2024",
    brand: "Toyota",
    model: "Corolla Cross",
    version: "XEI HV",
    type: "nuevos",
    year: 2024,
    km: 0,
    priceArs: 59800000,
    transmission: "Automatica",
    fuel: "Hibrido",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: true,
  },
  {
    id: "veh-1014",
    slug: "bmw-g-310-gs-abs-2023",
    brand: "BMW",
    model: "G 310 GS",
    version: "ABS",
    type: "motos",
    year: 2023,
    km: 4900,
    priceArs: 12300000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
  {
    id: "veh-1015",
    slug: "honda-xr-190l-2022",
    brand: "Honda",
    model: "XR 190L",
    version: "Base",
    type: "motos",
    year: 2022,
    km: 8700,
    priceArs: 7400000,
    transmission: "Manual",
    fuel: "Nafta",
    coverImage: DEFAULT_IMAGE,
    images: [DEFAULT_IMAGE],
    isFeatured: false,
  },
];
